### PR TITLE
Exception while invoking method 'editableJSON_update' ReferenceError:…

### PR DESCRIPTION
**Pull request by chrisbutler**
… check is not defined

### CODE REVIEW

**Comment by JackAdams** [comment]
Thanks for that. I'll add that dependency and get a new release out soon.

**Comment by chrisbutler** [comment]
:+1:

**Comment by chrisbutler** [comment]
@JackAdams is this going to be updated on atmosphere soon?

**Comment by JackAdams** [comment]
Yes, it will.  Sorry about the delay!

As far as I know, the `editable-json` package is only used as a dependency by the Constellation packages and, since I'm working on an update of the Constellation core, I was going to release them all together.

I guess Constellation is currently breaking apps that don't have `check` added as a dependency, right?  I'll try to push up the timeline.

**Comment by JackAdams** [comment]
Okay. 1.2.2 (just released on atmosphere) should have the contents of this PR included.

**Comment by chrisbutler** [comment]
awesome! you're the man

**Pull request merged**
